# Generated by Django 4.2 on 2023-05-02 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('birth_date', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('avatar', models.ImageField(default='profile/default-avatar.png', upload_to='profile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.eventgroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
