# Generated by Django 4.2 on 2023-05-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_leave_data_eventgroup_leave_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventgroup',
            old_name='leave_date',
            new_name='leave_data',
        ),
    ]
