# Generated by Django 4.2 on 2023-05-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='img',
        ),
    ]
